#!/bin/bash


chmod +x ~/binder/start.hadoop 
service vsftpd start



~/binder/start.hadoop  		&& \
sleep 3                		&& \
touch ready.txt         	&



# DO NOT REMOVE(!) 
# Here is why: https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"
